import os


MODEL4_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(os.path.dirname(MODEL4_DIR))

# ============== Paths ==============
LOG_DIR = os.path.join(PROJECT_ROOT, "logs")
AIRSIM_NAV_CACHE_JSON = os.path.join(LOG_DIR, "model4_airsim_midgoal_points.json")
AIRSIM_NAV_CACHE_VERSION = 2
MODEL1_CHECKPOINT_DIR = os.path.join(PROJECT_ROOT, "Network", "Model1", "checkpoints")

# ============== AirSim Sensors ==============
PRIMARY_LIDAR_NAME = "RLoPlannerLidar"
FALLBACK_LIDAR_NAMES = ("Lidar1", "LLidar1")
RANGE_MAX = 10.0
RANGE_HFOV = 90.0
RANGE_VFOV = 60.0
RANGE_RAYS_H = 5
RANGE_RAYS_V = 5
RANGE_MATCH_MARGIN = 1.2

# ============== Navigation Sampling ==============
AIRSIM_NAV_CACHE_POINTS = 160
AIRSIM_NAV_MIN_POINTS = 60
AIRSIM_NAV_MAX_ATTEMPTS = 4000
AIRSIM_NAV_ALTITUDES = (-3.0, -5.0, -7.0)
AIRSIM_NAV_FLIGHT_HEIGHTS = (3.0, 5.0, 7.0)
AIRSIM_NAV_POINT_CLEARANCE = 3.0
AIRSIM_NAV_MIN_POINT_SEPARATION = 8.0
AIRSIM_NAV_MIN_PAIR_DISTANCE = 12.0
AIRSIM_NAV_MAX_PAIR_DISTANCE = 35.0
AIRSIM_NAV_REGION_BUCKET = 20.0
AIRSIM_NAV_BOTTOM_MIN = 2.0
AIRSIM_NAV_BOTTOM_MAX = 12.0
AIRSIM_NAV_PROBE_SETTLE_SEC = 0.08
AIRSIM_NAV_BOUNDS_MARGIN = 8.0
AIRSIM_NAV_FALLBACK_RADIUS = 60.0
AIRSIM_NAV_OBJECT_SAMPLE = 800
AIRSIM_NAV_BOUNDS_PERCENTILE_LOW = 2.0
AIRSIM_NAV_BOUNDS_PERCENTILE_HIGH = 98.0
AIRSIM_NAV_FORCE_REBUILD = False
AIRSIM_NAV_NAVIGABLE_KEYWORDS = ("street", "sidewalk", "curb")
AIRSIM_NAV_ANCHOR_JITTER = (0.0, 2.5, 5.0)
AIRSIM_NAV_MAX_ANCHORS_PER_REBUILD = 600
AIRSIM_NAV_MAX_CANDIDATES_PER_REBUILD = 6000
AIRSIM_NAV_GRAPH_NEIGHBOR_RADIUS = 35.0
AIRSIM_NAV_GRAPH_MAX_NEIGHBORS = 8
AIRSIM_NAV_GLOBAL_MIN_DISTANCE = 80.0
AIRSIM_NAV_GLOBAL_MAX_DISTANCE = 220.0
AIRSIM_NAV_SUBGOAL_SPACING = 30.0
AIRSIM_NAV_SUBGOAL_MIN_SPACING = 18.0

# ============== Model1 Training Bridge ==============
TRAIN_TIMESTEPS = 300000
TRAIN_SEED = 42
